services:
  fronius-bridge:
    image: lerebel103/fronius-ha-dual-mppt:latest
    pull_policy: always
    container_name: fronius-ha-dual-mppt
    restart: unless-stopped
    
    # Mount local config file to container
    volumes:
      - ./config.yaml:/etc/fronius-ha-dual-mppt/config.yaml:rw
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ:-Australia/Perth}
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
